// Generated by scripts/generate.mjs — do not edit by hand.
//
// Every locale, synchronously. Convenient where size does not matter — build
// scripts, servers, tests. In a browser bundle prefer locales/<tag> or load.
import { LOCALES } from "./index.js"
import { unsupportedLocale } from "./internal.js"
import locale_ar from "./locales/ar.js"
import locale_bg from "./locales/bg.js"
import locale_cs from "./locales/cs.js"
import locale_da from "./locales/da.js"
import locale_de from "./locales/de.js"
import locale_el from "./locales/el.js"
import locale_en from "./locales/en.js"
import locale_es from "./locales/es.js"
import locale_fi from "./locales/fi.js"
import locale_fr from "./locales/fr.js"
import locale_he from "./locales/he.js"
import locale_hu from "./locales/hu.js"
import locale_it from "./locales/it.js"
import locale_ja from "./locales/ja.js"
import locale_ko from "./locales/ko.js"
import locale_nl from "./locales/nl.js"
import locale_no from "./locales/no.js"
import locale_pl from "./locales/pl.js"
import locale_pt_BR from "./locales/pt-BR.js"
import locale_pt_PT from "./locales/pt-PT.js"
import locale_ro from "./locales/ro.js"
import locale_ru from "./locales/ru.js"
import locale_sv from "./locales/sv.js"
import locale_tr from "./locales/tr.js"
import locale_vi from "./locales/vi.js"
import locale_zh_Hans from "./locales/zh-Hans.js"
import locale_zh_Hant from "./locales/zh-Hant.js"

const BUNDLES = {
  "ar": locale_ar,
  "bg": locale_bg,
  "cs": locale_cs,
  "da": locale_da,
  "de": locale_de,
  "el": locale_el,
  "en": locale_en,
  "es": locale_es,
  "fi": locale_fi,
  "fr": locale_fr,
  "he": locale_he,
  "hu": locale_hu,
  "it": locale_it,
  "ja": locale_ja,
  "ko": locale_ko,
  "nl": locale_nl,
  "no": locale_no,
  "pl": locale_pl,
  "pt-BR": locale_pt_BR,
  "pt-PT": locale_pt_PT,
  "ro": locale_ro,
  "ru": locale_ru,
  "sv": locale_sv,
  "tr": locale_tr,
  "vi": locale_vi,
  "zh-Hans": locale_zh_Hans,
  "zh-Hant": locale_zh_Hant,
}

/**
 * Every disclosure for a locale, ready to render.
 *
 * Hand it the locale your app already resolved. It does not sniff, negotiate,
 * or quietly fall back: guessing the language of a legal declaration is worse
 * than failing loudly.
 *
 * @throws code ERR_UNSUPPORTED_LOCALE if the locale has no bundle.
 */
export function getDisclosures(locale) {
  if (typeof locale !== "string" || !Object.hasOwn(BUNDLES, locale)) {
    throw unsupportedLocale(locale, LOCALES)
  }
  return BUNDLES[locale]
}
