// Generated by scripts/generate.mjs — do not edit by hand.
import type { Disclosures, Locale } from "./index.js"

/**
 * Every disclosure for a locale, synchronously. Carries every locale — prefer
 * `locales/<tag>` or `load` in a browser bundle.
 *
 * @throws code ERR_UNSUPPORTED_LOCALE if the locale has no bundle.
 */
export declare function getDisclosures<L extends Locale>(locale: L): Disclosures<L>
export declare function getDisclosures(locale: string): Disclosures
