// Generated by scripts/generate.mjs — do not edit by hand.
//
// The contract, and nothing else: keys, groups, guards and the grouping rule.
// No locale data — the whole module is about a kilobyte gzipped. Labels come
// from one of:
//
//   import de from "@menuella/food-safety/locales/de"          one locale, static
//   import { loadDisclosures } from "@menuella/food-safety/load" one locale, on demand
//   import { getDisclosures } from "@menuella/food-safety/all"   every locale, sync

/** Locales with a prebuilt bundle, as BCP 47 tags. */
export const LOCALES = Object.freeze(["ar", "bg", "cs", "da", "de", "el", "en", "es", "fi", "fr", "he", "hu", "it", "ja", "ko", "nl", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sv", "tr", "vi", "zh-Hans", "zh-Hant"])

/** The locale a bundle falls back to for anything it does not itself carry. */
export const FALLBACK_LOCALE = "en"

export const ALLERGEN_KEYS = Object.freeze(["RYE", "BARLEY", "EMMER", "EINKORN", "SPELT", "WHEAT", "OATS", "KHORASAN", "CRUSTACEANS", "EGGS", "FISH", "PEANUTS", "SOY", "MILK", "MACADAMIA", "ALMONDS", "BRAZIL_NUTS", "PECANS", "PISTACHIOS", "WALNUTS", "CASHEWS", "HAZELNUTS", "CELERY", "MUSTARD", "SESAME", "SULPHITES", "LUPINS", "MOLLUSCS"])
export const DECLARATION_KEYS = Object.freeze(["COLORING", "PRESERVATIVES", "ANTIOXIDANTS", "NITRITE_CURING_SALT", "NITRATE", "NITRITE_CURING_SALT_AND_NITRATE", "FLAVOR_ENHANCERS", "PHOSPHATE", "SULPHURED", "BLACKENED", "WAXED", "SWEETENERS", "PHENYLALANINE", "LAXATIVE_WARNING", "CAFFEINE", "QUININE", "CHILD_ATTENTION_WARNING", "MILK_PROTEIN", "SURIMI", "RECONSTITUTED_MEAT", "RECONSTITUTED_FISH", "DEFROSTED"])
export const ALLERGEN_GROUPS = Object.freeze(["CELERY", "CEREALS", "CRUSTACEANS", "EGGS", "FISH", "LUPINS", "MILK", "MOLLUSCS", "MUSTARD", "PEANUTS", "SESAME", "SOY", "SULPHITES", "TREE_NUTS"])
export const DECLARATION_CATEGORIES = Object.freeze(["ADDITIVE", "BEVERAGE", "PRODUCT", "WARNING"])
export const ICON_NAMES = Object.freeze(["celery", "cereals", "crustaceans", "declarations", "eggs", "fish", "lupins", "milk", "molluscs", "mustard", "peanuts", "sesame", "soy", "sulphites", "tree-nuts"])
export const CODE_SCHEME = "MENUELLA"

const allergenSet = new Set(ALLERGEN_KEYS)
const declarationSet = new Set(DECLARATION_KEYS)
const localeSet = new Set(LOCALES)

/**
 * True when the value is a current allergen key.
 *
 * Retired codes ("A6", "G") are NOT keys and return false — which is the point:
 * run stored data through this to find rows that still hold codes.
 */
export const isAllergenKey = (value) => typeof value === "string" && allergenSet.has(value)

/** True when the value is a current declaration key. Retired numbers return false. */
export const isDeclarationKey = (value) => typeof value === "string" && declarationSet.has(value)

/**
 * True when the value is a locale this package ships a bundle for. Exact match:
 * "pt-BR" is a locale, "pt-br" and "pt" are not.
 */
export const isLocale = (value) => typeof value === "string" && localeSet.has(value)

/**
 * The disclosures a product carries, arranged the way they must be rendered.
 *
 * Allergens come back grouped: the legal declaration is stated once per group
 * ("Contains cereals containing gluten"), with the specific members beneath it
 * (wheat, barley). Groups and declarations follow the dataset's order, not the
 * input's, so the same product always renders the same way.
 *
 * A key that is not in the vocabulary — a retired code, or a key from a newer
 * release of this package — is returned in `unknown` rather than dropped. On
 * an allergen panel, showing a raw key is better than silently showing less.
 */
export function resolveDisclosures(disclosures, keys) {
  // A string is iterable too: "WHEAT" would be read as the keys W, H, E, A, T,
  // and every one of them would come back as unknown.
  if (typeof keys === "string") {
    throw new TypeError("resolveDisclosures expects a list of keys, not a single string")
  }
  const wanted = new Set(keys)
  const groups = []
  const byGroup = new Map()
  for (const allergen of disclosures.allergens) {
    if (!wanted.has(allergen.key)) continue
    let entry = byGroup.get(allergen.group)
    if (entry === undefined) {
      entry = {
        group: allergen.group,
        declaration: allergen.declaration,
        icon: allergen.icon,
        members: [],
      }
      byGroup.set(allergen.group, entry)
      groups.push(entry)
    }
    if (allergen.isMember) entry.members.push(allergen)
  }
  const declarations = disclosures.declarations.filter((d) => wanted.has(d.key))
  const unknown = [...wanted].filter((k) => !isAllergenKey(k) && !isDeclarationKey(k))
  return { allergens: groups, declarations, unknown }
}
