// Generated by scripts/generate.mjs — do not edit by hand.
//
// The vocabularies and type guards, and nothing else. This module does NOT do
// i18n: locale resolution and fallback belong to whatever the app already uses
// (next-intl, i18next, Astro i18n), so the package ships one ready-to-render
// file per locale and the app imports the one it resolved:
//
//   import disclosures from "@menuella/food-safety/bundles/de.json"

import deBundle from "./data/bundles/de.js"
import enBundle from "./data/bundles/en.js"
import esBundle from "./data/bundles/es.js"
import frBundle from "./data/bundles/fr.js"
import itBundle from "./data/bundles/it.js"
import trBundle from "./data/bundles/tr.js"

/** Locales with a prebuilt bundle. */
export const LOCALES = Object.freeze(["de", "en", "es", "fr", "it", "tr"])

const BUNDLES = /* @__PURE__ */ { de: deBundle, en: enBundle, es: esBundle, fr: frBundle, it: itBundle, tr: trBundle }

/** The locale a bundle falls back to for anything it does not itself carry. */
export const FALLBACK_LOCALE = "en"

export const ALLERGEN_KEYS = Object.freeze(["RYE", "BARLEY", "EMMER", "EINKORN", "SPELT", "WHEAT", "OATS", "KHORASAN", "CRUSTACEANS", "EGGS", "FISH", "PEANUTS", "SOY", "MILK", "MACADAMIA", "ALMONDS", "BRAZIL_NUTS", "PECANS", "PISTACHIOS", "WALNUTS", "CASHEWS", "HAZELNUTS", "CELERY", "MUSTARD", "SESAME", "SULPHITES", "LUPINS", "MOLLUSCS"])
export const DECLARATION_KEYS = Object.freeze(["COLORING", "PRESERVATIVES", "ANTIOXIDANTS", "NITRITE_CURING_SALT", "NITRATE", "NITRITE_CURING_SALT_AND_NITRATE", "FLAVOR_ENHANCERS", "PHOSPHATE", "SULPHURED", "BLACKENED", "WAXED", "SWEETENERS", "PHENYLALANINE", "LAXATIVE_WARNING", "CAFFEINE", "QUININE", "CHILD_ATTENTION_WARNING", "MILK_PROTEIN", "SURIMI", "RECONSTITUTED_MEAT", "RECONSTITUTED_FISH", "DEFROSTED"])
export const ALLERGEN_GROUPS = Object.freeze(["CELERY", "CEREALS", "CRUSTACEANS", "EGGS", "FISH", "LUPINS", "MILK", "MOLLUSCS", "MUSTARD", "PEANUTS", "SESAME", "SOY", "SULPHITES", "TREE_NUTS"])
export const DECLARATION_CATEGORIES = Object.freeze(["ADDITIVE", "BEVERAGE", "PRODUCT", "WARNING"])
export const ICON_NAMES = Object.freeze(["celery", "cereals", "crustaceans", "declarations", "eggs", "fish", "lupins", "milk", "molluscs", "mustard", "peanuts", "sesame", "soy", "sulphites", "tree-nuts"])
export const CODE_SCHEME = "MENUELLA"

const allergenSet = new Set(ALLERGEN_KEYS)
const declarationSet = new Set(DECLARATION_KEYS)
const localeSet = new Set(LOCALES)

/**
 * Bundles are module-level singletons shared by every caller, so a consumer
 * that mutated one would corrupt the dataset for the whole process. Freezing
 * happens on first access rather than at module scope: a top-level call would
 * be an impure statement, and bundlers would stop tree-shaking the locale data
 * away for consumers that never ask for it.
 */
const deepFreeze = (value) => {
  if (value !== null && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value)
    for (const inner of Object.values(value)) deepFreeze(inner)
  }
  return value
}

/**
 * True when the value is a current allergen key.
 *
 * Retired codes ("A6", "G") are NOT keys and return false — which is the point:
 * run stored data through this to find rows that still hold codes.
 */
export const isAllergenKey = (value) => typeof value === "string" && allergenSet.has(value)

/** True when the value is a current declaration key. Retired numbers return false. */
export const isDeclarationKey = (value) => typeof value === "string" && declarationSet.has(value)

/** True when the value is a locale this package ships a bundle for. */
export const isLocale = (value) => typeof value === "string" && localeSet.has(value)

/**
 * Every disclosure for a locale, ready to render.
 *
 * Hand it the locale your app already resolved — `useLocale()` from next-intl,
 * `Astro.currentLocale`, whatever you use. This does NOT do i18n: it will not
 * sniff the browser, negotiate, or quietly fall back, because guessing the
 * language of a legal declaration is worse than failing loudly.
 *
 * ```ts
 * const { allergens, declarations } = getDisclosures(useLocale())
 * ```
 *
 * Unsupported locale? Decide the policy yourself, in one line:
 * `getDisclosures(LOCALES.includes(l) ? l : "en")`
 *
 * @throws if the locale has no bundle.
 */
export function getDisclosures(locale) {
  const bundle = Object.hasOwn(BUNDLES, locale) ? BUNDLES[locale] : undefined
  if (bundle === undefined) {
    const error = new Error(
      `No disclosures for locale "${locale}". Available: ${LOCALES.join(", ")}.`,
    )
    error.code = "ERR_UNSUPPORTED_LOCALE"
    throw error
  }
  return deepFreeze(bundle)
}
