// Generated by scripts/generate.mjs — do not edit by hand.
//
// One dynamic import per locale, each with a literal specifier, so every
// bundler can see them and split each locale into its own chunk.
import { LOCALES } from "./index.js"
import { unsupportedLocale } from "./internal.js"

const LOADERS = {
  "ar": () => import("./locales/ar.js"),
  "bg": () => import("./locales/bg.js"),
  "cs": () => import("./locales/cs.js"),
  "da": () => import("./locales/da.js"),
  "de": () => import("./locales/de.js"),
  "el": () => import("./locales/el.js"),
  "en": () => import("./locales/en.js"),
  "es": () => import("./locales/es.js"),
  "fi": () => import("./locales/fi.js"),
  "fr": () => import("./locales/fr.js"),
  "he": () => import("./locales/he.js"),
  "hu": () => import("./locales/hu.js"),
  "it": () => import("./locales/it.js"),
  "ja": () => import("./locales/ja.js"),
  "ko": () => import("./locales/ko.js"),
  "nl": () => import("./locales/nl.js"),
  "no": () => import("./locales/no.js"),
  "pl": () => import("./locales/pl.js"),
  "pt-BR": () => import("./locales/pt-BR.js"),
  "pt-PT": () => import("./locales/pt-PT.js"),
  "ro": () => import("./locales/ro.js"),
  "ru": () => import("./locales/ru.js"),
  "sv": () => import("./locales/sv.js"),
  "tr": () => import("./locales/tr.js"),
  "vi": () => import("./locales/vi.js"),
  "zh-Hans": () => import("./locales/zh-Hans.js"),
  "zh-Hant": () => import("./locales/zh-Hant.js"),
}

/**
 * Every disclosure for a locale, fetched on demand. Resolves to the same
 * frozen object `locales/<tag>` exports.
 *
 * Rejects with code ERR_UNSUPPORTED_LOCALE for a locale without a bundle —
 * it does not negotiate or fall back.
 */
export function loadDisclosures(locale) {
  if (typeof locale !== "string" || !Object.hasOwn(LOADERS, locale)) {
    return Promise.reject(unsupportedLocale(locale, LOCALES))
  }
  return LOADERS[locale]().then((module) => module.default)
}
