// Generated by scripts/generate.mjs — do not edit by hand.
import type { Disclosures, Locale } from "./index.js"

/**
 * Every disclosure for a locale, fetched on demand — only that locale's data
 * is downloaded. Rejects with code ERR_UNSUPPORTED_LOCALE for a locale
 * without a bundle.
 */
export declare function loadDisclosures<L extends Locale>(locale: L): Promise<Disclosures<L>>
export declare function loadDisclosures(locale: string): Promise<Disclosures>
