// Generated by scripts/generate.mjs — do not edit by hand.
import { deepFreeze } from "../internal.js"
import bundle from "../data/bundles/pt-BR.js"

export default /* @__PURE__ */ deepFreeze(bundle)
