// GENERATED by scripts/generate.mjs — do not edit by hand.
package com.menuella.foodsafety

internal val GENERATED_LOCALES: List<String> = listOf("de", "en", "es", "fr", "it", "tr")
internal const val GENERATED_FALLBACK_LOCALE: String = "en"
internal const val GENERATED_CODE_SCHEME: String = "MENUELLA"
internal val GENERATED_ALLERGEN_KEYS: List<String> = listOf("RYE", "BARLEY", "EMMER", "EINKORN", "SPELT", "WHEAT", "OATS", "KHORASAN", "CRUSTACEANS", "EGGS", "FISH", "PEANUTS", "SOY", "MILK", "MACADAMIA", "ALMONDS", "BRAZIL_NUTS", "PECANS", "PISTACHIOS", "WALNUTS", "CASHEWS", "HAZELNUTS", "CELERY", "MUSTARD", "SESAME", "SULPHITES", "LUPINS", "MOLLUSCS")
internal val GENERATED_DECLARATION_KEYS: List<String> = listOf("COLORING", "PRESERVATIVES", "ANTIOXIDANTS", "NITRITE_CURING_SALT", "NITRATE", "NITRITE_CURING_SALT_AND_NITRATE", "FLAVOR_ENHANCERS", "PHOSPHATE", "SULPHURED", "BLACKENED", "WAXED", "SWEETENERS", "PHENYLALANINE", "LAXATIVE_WARNING", "CAFFEINE", "QUININE", "CHILD_ATTENTION_WARNING", "MILK_PROTEIN", "SURIMI", "RECONSTITUTED_MEAT", "RECONSTITUTED_FISH", "DEFROSTED")

internal fun bundleFor(locale: String): Disclosures? = when (locale) {
  "de" -> bundleDE()
  "en" -> bundleEN()
  "es" -> bundleES()
  "fr" -> bundleFR()
  "it" -> bundleIT()
  "tr" -> bundleTR()
  else -> null
}
