// GENERATED by scripts/generate.mjs — do not edit by hand.
package com.menuella.foodsafety

internal val GENERATED_LOCALES: List<String> = listOf("ar", "bg", "cs", "da", "de", "el", "en", "es", "fi", "fr", "he", "hu", "it", "ja", "ko", "nl", "no", "pl", "pt", "ro", "ru", "sv", "tr", "vi", "zh")
internal const val GENERATED_FALLBACK_LOCALE: String = "en"
internal const val GENERATED_CODE_SCHEME: String = "MENUELLA"
internal val GENERATED_ALLERGEN_KEYS: List<String> = listOf("RYE", "BARLEY", "EMMER", "EINKORN", "SPELT", "WHEAT", "OATS", "KHORASAN", "CRUSTACEANS", "EGGS", "FISH", "PEANUTS", "SOY", "MILK", "MACADAMIA", "ALMONDS", "BRAZIL_NUTS", "PECANS", "PISTACHIOS", "WALNUTS", "CASHEWS", "HAZELNUTS", "CELERY", "MUSTARD", "SESAME", "SULPHITES", "LUPINS", "MOLLUSCS")
internal val GENERATED_DECLARATION_KEYS: List<String> = listOf("COLORING", "PRESERVATIVES", "ANTIOXIDANTS", "NITRITE_CURING_SALT", "NITRATE", "NITRITE_CURING_SALT_AND_NITRATE", "FLAVOR_ENHANCERS", "PHOSPHATE", "SULPHURED", "BLACKENED", "WAXED", "SWEETENERS", "PHENYLALANINE", "LAXATIVE_WARNING", "CAFFEINE", "QUININE", "CHILD_ATTENTION_WARNING", "MILK_PROTEIN", "SURIMI", "RECONSTITUTED_MEAT", "RECONSTITUTED_FISH", "DEFROSTED")

internal fun bundleFor(locale: String): Disclosures? = when (locale) {
  "ar" -> bundleAR()
  "bg" -> bundleBG()
  "cs" -> bundleCS()
  "da" -> bundleDA()
  "de" -> bundleDE()
  "el" -> bundleEL()
  "en" -> bundleEN()
  "es" -> bundleES()
  "fi" -> bundleFI()
  "fr" -> bundleFR()
  "he" -> bundleHE()
  "hu" -> bundleHU()
  "it" -> bundleIT()
  "ja" -> bundleJA()
  "ko" -> bundleKO()
  "nl" -> bundleNL()
  "no" -> bundleNO()
  "pl" -> bundlePL()
  "pt" -> bundlePT()
  "ro" -> bundleRO()
  "ru" -> bundleRU()
  "sv" -> bundleSV()
  "tr" -> bundleTR()
  "vi" -> bundleVI()
  "zh" -> bundleZH()
  else -> null
}
