#!/usr/bin/env node
// Regenerates everything derived from the hand-maintained sources.
//
//   sources      data/{allergens,declarations,ingredients}.json
//                data/translations/<module>/<lang>.json
//                data/codes.json
//   generated    data/bundles/<lang>.json
//                index.js  index.d.ts
//
// Run after editing any source file:  npm run generate
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { execFileSync } from "node:child_process"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const DATA = join(ROOT, "data")

// Sources are always read from the repo. Output normally goes back to the repo,
// but `--out <dir>` sends it elsewhere — which is how `verify` compares the
// committed files against a fresh build without touching the working tree.
const outFlag = process.argv.indexOf("--out")
const OUT = outFlag === -1 ? ROOT : resolve(process.argv[outFlag + 1])

const read = (p) => JSON.parse(readFileSync(join(DATA, p), "utf8"))
const ensureDir = (abs) => {
  mkdirSync(dirname(abs), { recursive: true })
  return abs
}
const write = (abs, value) => {
  writeFileSync(ensureDir(abs), `${JSON.stringify(value, null, 2)}\n`, "utf8")
}
const locales = () =>
  readdirSync(join(DATA, "translations", "allergens"))
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""))
    .sort()

const allergens = read("allergens.json")
const declarations = read("declarations.json")
const codes = read("codes.json")
const LOCALES = locales()
const FALLBACK = "en"

// ---------------------------------------------------------------- bundles ---
// Structure + labels + icon, pre-joined, so a client renders without a lookup
// of its own. Any field a locale does not carry falls back — and every
// substitution is recorded, so a fallback is inspectable rather than silent.
for (const locale of LOCALES) {
  const labels = {
    allergens: read(`translations/allergens/${locale}.json`),
    declarations: read(`translations/declarations/${locale}.json`),
  }
  const fallbackLabels = {
    allergens: read(`translations/allergens/${FALLBACK}.json`),
    declarations: read(`translations/declarations/${FALLBACK}.json`),
  }
  const fallbacks = []

  const entry = (module, item, extra) => {
    const own = labels[module][item.key] ?? {}
    const base = fallbackLabels[module][item.key] ?? {}
    const out = { key: item.key, ...extra, icon: item.icon }
    for (const field of ["name", "declaration", "description"]) {
      if (!(field in base) && !(field in own)) continue
      if (own[field]) {
        out[field] = own[field]
      } else {
        out[field] = base[field]
        fallbacks.push(`${module}.${item.key}.${field}`)
      }
    }
    return out
  }

  const bundle = {
    locale,
    fallbackLocale: FALLBACK,
    allergens: allergens.map((a) =>
      entry("allergens", a, { group: a.group, isMember: a.isMember }),
    ),
    declarations: declarations.map((a) => entry("declarations", a, { category: a.category })),
    fallbacks: fallbacks.sort(),
  }
  write(join(OUT, "data", "bundles", `${locale}.json`), bundle)
  writeFileSync(
    ensureDir(join(OUT, "data", "bundles", `${locale}.js`)),
    `// Generated by scripts/generate.mjs — do not edit by hand.\n` +
      `export default ${JSON.stringify(bundle, null, 2)}\n`,
    "utf8",
  )
}

// ------------------------------------------------------- index.js / .d.ts ---
const A_KEYS = allergens.map((a) => a.key)
const D_KEYS = declarations.map((a) => a.key)
const GROUPS = [...new Set(allergens.map((a) => a.group))].sort()
const CATEGORIES = [...new Set(declarations.map((a) => a.category))].sort()
const ICONS = [...new Set([...allergens, ...declarations].map((a) => a.icon))].sort()

const arr = (values) => values.map((v) => `"${v}"`).join(", ")
const union = (values) => values.map((v) => `"${v}"`).join("\n  | ")

writeFileSync(
  ensureDir(join(OUT, "index.js")),
  `// Generated by scripts/generate.mjs — do not edit by hand.
//
// The vocabularies and type guards, and nothing else. This module does NOT do
// i18n: locale resolution and fallback belong to whatever the app already uses
// (next-intl, i18next, Astro i18n), so the package ships one ready-to-render
// file per locale and the app imports the one it resolved:
//
//   import disclosures from "@menuella/food-safety/bundles/de.json"

${LOCALES.map((l) => `import ${l}Bundle from "./data/bundles/${l}.js"`).join("\n")}

/** Locales with a prebuilt bundle. */
export const LOCALES = Object.freeze([${arr(LOCALES)}])

const BUNDLES = /* @__PURE__ */ { ${LOCALES.map((l) => `${l}: ${l}Bundle`).join(", ")} }

/** The locale a bundle falls back to for anything it does not itself carry. */
export const FALLBACK_LOCALE = "${FALLBACK}"

export const ALLERGEN_KEYS = Object.freeze([${arr(A_KEYS)}])
export const DECLARATION_KEYS = Object.freeze([${arr(D_KEYS)}])
export const ALLERGEN_GROUPS = Object.freeze([${arr(GROUPS)}])
export const DECLARATION_CATEGORIES = Object.freeze([${arr(CATEGORIES)}])
export const ICON_NAMES = Object.freeze([${arr(ICONS)}])
export const CODE_SCHEME = "${codes.scheme}"

const allergenSet = new Set(ALLERGEN_KEYS)
const declarationSet = new Set(DECLARATION_KEYS)
const localeSet = new Set(LOCALES)

/**
 * Bundles are module-level singletons shared by every caller, so a consumer
 * that mutated one would corrupt the dataset for the whole process. Freezing
 * happens on first access rather than at module scope: a top-level call would
 * be an impure statement, and bundlers would stop tree-shaking the locale data
 * away for consumers that never ask for it.
 */
const deepFreeze = (value) => {
  if (value !== null && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value)
    for (const inner of Object.values(value)) deepFreeze(inner)
  }
  return value
}

/**
 * True when the value is a current allergen key.
 *
 * Retired codes ("A6", "G") are NOT keys and return false — which is the point:
 * run stored data through this to find rows that still hold codes.
 */
export const isAllergenKey = (value) => typeof value === "string" && allergenSet.has(value)

/** True when the value is a current declaration key. Retired numbers return false. */
export const isDeclarationKey = (value) => typeof value === "string" && declarationSet.has(value)

/** True when the value is a locale this package ships a bundle for. */
export const isLocale = (value) => typeof value === "string" && localeSet.has(value)

/**
 * Every disclosure for a locale, ready to render.
 *
 * Hand it the locale your app already resolved — \`useLocale()\` from next-intl,
 * \`Astro.currentLocale\`, whatever you use. This does NOT do i18n: it will not
 * sniff the browser, negotiate, or quietly fall back, because guessing the
 * language of a legal declaration is worse than failing loudly.
 *
 * \`\`\`ts
 * const { allergens, declarations } = getDisclosures(useLocale())
 * \`\`\`
 *
 * Unsupported locale? Decide the policy yourself, in one line:
 * \`getDisclosures(LOCALES.includes(l) ? l : "en")\`
 *
 * @throws if the locale has no bundle.
 */
export function getDisclosures(locale) {
  const bundle = Object.hasOwn(BUNDLES, locale) ? BUNDLES[locale] : undefined
  if (bundle === undefined) {
    const error = new Error(
      \`No disclosures for locale "\${locale}". Available: \${LOCALES.join(", ")}.\`,
    )
    error.code = "ERR_UNSUPPORTED_LOCALE"
    throw error
  }
  return deepFreeze(bundle)
}
`,
  "utf8",
)

writeFileSync(
  ensureDir(join(OUT, "index.d.ts")),
  `// Generated by scripts/generate.mjs — do not edit by hand.

/** A locale with a prebuilt bundle under \`bundles/\`. */
export type Locale =
  | ${union(LOCALES)}

/** One of the ${A_KEYS.length} selectable allergen disclosures. */
export type AllergenKey =
  | ${union(A_KEYS)}

/** One of the ${D_KEYS.length} Menuella Declarations. */
export type DeclarationKey =
  | ${union(D_KEYS)}

/** The ${GROUPS.length} EU allergen groups. Display grouping — never selectable. */
export type AllergenGroup =
  | ${union(GROUPS)}

/** What kind of declaration an entry is. */
export type DeclarationCategory =
  | ${union(CATEGORIES)}

/** Basename of an SVG in \`icons/\` — e.g. "cereals" is \`icons/cereals.svg\`. */
export type IconName =
  | ${union(ICONS)}

/** An allergen with its labels already resolved for one locale. */
export interface Allergen {
  key: AllergenKey
  group: AllergenGroup
  /** True for a specific member of a multi-member group (each cereal, each nut). */
  isMember: boolean
  icon: IconName
  /** Short label, e.g. "Weizen". */
  name: string
  /** Legal group sentence. Render ONCE per group, members listed beneath. */
  declaration: string
  description: string
}

/** A Menuella Declaration with its labels already resolved for one locale. */
export interface Declaration {
  key: DeclarationKey
  category: DeclarationCategory
  icon: IconName
  name: string
  description: string
}

/**
 * One locale's bundle — the shape of \`bundles/<locale>.json\`.
 *
 * Import it directly; there is no loader to call:
 * \`\`\`ts
 * import type { Disclosures } from "@menuella/food-safety"
 * import data from "@menuella/food-safety/bundles/de.json"
 * const disclosures = data as Disclosures
 * \`\`\`
 */
export interface Disclosures {
  locale: Locale
  fallbackLocale: "${FALLBACK}"
  allergens: Allergen[]
  declarations: Declaration[]
  /**
   * Fields served from the fallback locale, as "module.KEY.field" — e.g.
   * "allergens.WHEAT.declaration". Empty when the locale covers everything.
   * Present so a fallback is inspectable rather than silent.
   */
  fallbacks: string[]
}

/** The Menuella footnote codes — the shape of \`data/codes.json\`. */
export interface Codes {
  scheme: "${codes.scheme}"
  convention: string
  allergens: Record<AllergenKey, string>
  declarations: Record<DeclarationKey, string>
}

export declare const LOCALES: readonly Locale[]
export declare const FALLBACK_LOCALE: "${FALLBACK}"
export declare const ALLERGEN_KEYS: readonly AllergenKey[]
export declare const DECLARATION_KEYS: readonly DeclarationKey[]
export declare const ALLERGEN_GROUPS: readonly AllergenGroup[]
export declare const DECLARATION_CATEGORIES: readonly DeclarationCategory[]
export declare const ICON_NAMES: readonly IconName[]
export declare const CODE_SCHEME: "${codes.scheme}"

/**
 * True when the value is a current allergen key.
 * Retired codes ("A6", "G") return false — use this to find stored rows that
 * still hold codes.
 */
export declare function isAllergenKey(value: unknown): value is AllergenKey

/** True when the value is a current declaration key. Retired numbers return false. */
export declare function isDeclarationKey(value: unknown): value is DeclarationKey

/**
 * Every disclosure for a locale, ready to render.
 *
 * Hand it the locale your app already resolved — \`useLocale()\` from next-intl,
 * \`Astro.currentLocale\`, whatever you use. This does NOT do i18n: it will not
 * sniff the browser, negotiate, or quietly fall back.
 *
 * @throws if the locale has no bundle.
 */
export declare function getDisclosures(locale: Locale | (string & {})): Disclosures
`,
  "utf8",
)

// ------------------------------------------------------- data/icons.json ---
// The 15 glyphs, parsed out of icons/*.svg into structured nodes.
//
// Only the DATA is generated; icons.js is hand-written and imports this. The
// alternative — generating the module too — meant a template literal nested
// inside a template literal, which is how a generator starts emitting code
// nobody can read or debug.
//
// Structured rather than a markup string because the consumers differ: React
// and Svelte want real elements (an innerHTML escape hatch on a legal surface
// is a smell), while Astro, e-mail and PDF want a string. Shipping nodes lets
// getIconSvg build the string and everyone else build elements — one source,
// and no framework in the dependency list.
const ICON_DIR = join(ROOT, "icons")

// Attributes we accept on a child node. Anything else is a hand-edit the
// generator has not been taught, and is louder as a build failure than as a
// glyph that silently loses a corner.
const ATTR_MAP = {
  d: "d", cx: "cx", cy: "cy", r: "r",
  fill: "fill", "fill-rule": "fillRule", "clip-rule": "clipRule",
}

const parseIcon = (name, svg) => {
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1]
  if (!viewBox) throw new Error(`icons/${name}.svg: no viewBox`)

  const nodes = []
  // [\s\S] not . — fish.svg wraps its attributes across several lines.
  for (const m of svg.matchAll(/<(path|circle)\s([\s\S]*?)\/?>/g)) {
    const [, tag, raw] = m
    const attrs = {}
    for (const a of raw.matchAll(/([a-z-]+)="([^"]*)"/g)) {
      const [, key, value] = a
      const mapped = ATTR_MAP[key]
      if (!mapped) throw new Error(`icons/${name}.svg: unsupported attribute "${key}" on <${tag}>`)
      attrs[mapped] = value
    }
    // Every shape must paint with the text colour, or it cannot follow a
    // light/dark theme — the whole reason these are inlined rather than <img>.
    if (attrs.fill !== "currentColor") {
      throw new Error(`icons/${name}.svg: <${tag}> needs fill="currentColor", got "${attrs.fill ?? "none"}"`)
    }
    nodes.push([tag, attrs])
  }
  if (nodes.length === 0) throw new Error(`icons/${name}.svg: no <path> or <circle>`)
  return { viewBox, nodes }
}

const iconData = {}
for (const file of readdirSync(ICON_DIR).filter((f) => f.endsWith(".svg")).sort()) {
  const name = file.replace(/\.svg$/, "")
  iconData[name] = parseIcon(name, readFileSync(join(ICON_DIR, file), "utf8"))
}
const iconNames = Object.keys(iconData)

const noGlyph = ICONS.filter((i) => !iconNames.includes(i))
if (noGlyph.length > 0) throw new Error(`data references icons with no SVG: ${noGlyph.join(", ")}`)

write(join(OUT, "data", "icons.json"), iconData)
// A .js twin as well, exactly like the bundles: icons.js imports the data, and
// `import ... with { type: "json" }` needs Node 20.10 while this package
// supports 18.
writeFileSync(
  ensureDir(join(OUT, "data", "icons.js")),
  `// Generated by scripts/generate.mjs — do not edit by hand.\nexport default ${JSON.stringify(iconData, null, 2)}\n`,
  "utf8",
)


// -------------------------------------------------- packages/dart/**.g.dart --
// Dart gets GENERATED SOURCE rather than a data file it reads at runtime.
// dart:io does not exist on the web, so a package that reads JSON from disk
// cannot be used from Flutter web at all — and a Flutter package that only
// works on half its platforms is not a Dart package.
//
// The generator is the same one that writes index.js, from the same JSON, so
// this is no more a "second copy" than the JS bundles are.
const dq = (v) => JSON.stringify(String(v))
const dartList = (values) => `<String>[${values.map(dq).join(", ")}]`

const dartAllergen = (a) =>
  `A(${dq(a.key)}, ${dq(a.group)}, ${a.isMember}, ${dq(a.icon)}, ${dq(a.name)}, ` +
  `${dq(a.declaration)}, ${dq(a.description)})`

const dartDeclaration = (d) =>
  `D(${dq(d.key)}, ${dq(d.category)}, ${dq(d.icon)}, ${dq(d.name)}, ${dq(d.description)})`

const bundleFor = (locale) => JSON.parse(readFileSync(join(OUT, `data/bundles/${locale}.json`), "utf8"))

writeFileSync(
  ensureDir(join(OUT, "packages/dart/lib/src/data.g.dart")),
  `// GENERATED by scripts/generate.mjs — do not edit by hand.
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs

import 'models.dart';

// Short aliases keep this file readable at ${LOCALES.length} locales x ${A_KEYS.length + D_KEYS.length} entries.
typedef A = Allergen;
typedef D = Declaration;

const List<String> kLocales = ${dartList(LOCALES)};
const String kFallbackLocale = ${dq(FALLBACK)};
const String kCodeScheme = ${dq(codes.scheme)};
const List<String> kAllergenKeys = ${dartList(A_KEYS)};
const List<String> kDeclarationKeys = ${dartList(D_KEYS)};
const List<String> kIconNames = ${dartList(ICONS)};

const Map<String, DisclosureSet> kBundles = <String, DisclosureSet>{
${LOCALES.map((l) => {
  const b = bundleFor(l)
  return `  ${dq(l)}: DisclosureSet(
    locale: ${dq(b.locale)},
    fallbackLocale: ${dq(b.fallbackLocale)},
    allergens: <Allergen>[
${b.allergens.map((a) => `      ${dartAllergen(a)},`).join("\n")}
    ],
    declarations: <Declaration>[
${b.declarations.map((d) => `      ${dartDeclaration(d)},`).join("\n")}
    ],
  ),`
}).join("\n")}
};
`,
  "utf8",
)

writeFileSync(
  ensureDir(join(OUT, "packages/dart/lib/src/icons.g.dart")),
  `// GENERATED by scripts/generate.mjs from icons/*.svg — do not edit by hand.
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs

import 'models.dart';

// Attribute names are already in SVG spelling here (fill-rule, not fillRule):
// Dart has no JSX, so the React spelling would be wrong for every consumer.
const Map<String, Icon> kIcons = <String, Icon>{
${Object.entries(iconData).map(([name, icon]) => `  ${dq(name)}: Icon(
    viewBox: ${dq(icon.viewBox)},
    nodes: <IconNode>[
${icon.nodes.map(([tag, attrs]) => {
  const pairs = Object.entries(attrs)
    .map(([k, v]) => `${dq(k === "fillRule" ? "fill-rule" : k === "clipRule" ? "clip-rule" : k)}: ${dq(v)}`)
    .join(", ")
  return `      IconNode(${dq(tag)}, <String, String>{${pairs}}),`
}).join("\n")}
    ],
  ),`).join("\n")}
};
`,
  "utf8",
)

// `dart format` would otherwise rewrite what we just emitted, so every
// contributor who ran it would make the generated files look stale. Formatting
// here means the committed output IS the formatted output.
//
// Skipped when the Dart SDK is absent — a JS-only contributor should not need
// it installed, and verify.mjs skips the Dart diff in that case for the same
// reason.
//
// --language-version is load-bearing, not decoration. `dart format` picks its
// style from the package's language version in pubspec.yaml, and verify.mjs
// builds into a temp directory that has no pubspec — so without this flag the
// temp build gets the newer "tall" style, the committed file keeps the short
// one, and every verify run reports a stale file that is perfectly in sync.
try {
  execFileSync(
    "dart",
    ["format", "--language-version=3.6", join(OUT, "packages/dart/lib/src")],
    { stdio: "pipe" },
  )
} catch {
  console.log("note: dart not found — .g.dart emitted unformatted")
}

// ------------------------------------------- packages/python/**/data/*.json --
// Python ships the canonical JSON and reads it at runtime through
// importlib.resources. No generated source, because unlike Dart there is no
// platform here without a resource loader — so a code generator would buy
// nothing and add a second thing to keep in step.
//
// Copied rather than symlinked: a wheel is built from the source tree, and a
// symlink out of it resolves to nothing once installed.
const PY_DATA = join(OUT, "packages/python/src/menuella_food_safety/data")
for (const f of ["allergens.json", "declarations.json", "codes.json", "icons.json"]) {
  writeFileSync(ensureDir(join(PY_DATA, f)), readFileSync(join(DATA, f), "utf8"), "utf8")
}
for (const l of LOCALES) {
  writeFileSync(
    ensureDir(join(PY_DATA, "bundles", `${l}.json`)),
    readFileSync(join(OUT, `data/bundles/${l}.json`), "utf8"),
    "utf8",
  )
}
for (const f of ["README.md", "CHANGELOG.md", "LICENSE"]) {
  const src = f === "README.md" ? null : join(ROOT, f)
  if (src) writeFileSync(ensureDir(join(OUT, "packages/python", f)), readFileSync(src, "utf8"), "utf8")
}

// pub.dev requires these AT the package root — it cannot reference ../../ — so
// they are copied rather than symlinked (pub does not follow symlinks).
//
// README is NOT copied: pub.dev renders it as the package page, and the root
// README documents the npm entry points. A Dart developer landing on an `npm i`
// instruction has been sent to the wrong place. packages/dart/README.md is
// written by hand for that audience.
for (const f of ["CHANGELOG.md", "LICENSE"]) {
  writeFileSync(ensureDir(join(OUT, "packages/dart", f)), readFileSync(join(ROOT, f), "utf8"), "utf8")
}


// -------------------- packages/swift/**/Resources/*.json --
// Swift reads the JSON from its resource bundle: Foundation has JSONDecoder, so
// there is nothing to generate and no dependency to take. Copied in rather than
// read from ../../data, because SwiftPM resources must live inside the target.
const SWIFT_RES = join(OUT, "packages/swift/Sources/MenuellaFoodSafety/Resources")
for (const f of ["allergens.json", "declarations.json", "codes.json", "icons.json"]) {
  writeFileSync(ensureDir(join(SWIFT_RES, f)), readFileSync(join(DATA, f), "utf8"), "utf8")
}
for (const l of LOCALES) {
  writeFileSync(
    ensureDir(join(SWIFT_RES, "bundles", `${l}.json`)),
    readFileSync(join(OUT, `data/bundles/${l}.json`), "utf8"),
    "utf8",
  )
}

// ------------------------------ packages/php/data/*.json --
// PHP reads the JSON at runtime: json_decode is in core, so there is nothing to
// generate and nothing to depend on. Copied into the package rather than read
// from ../../data, so the path holds however the package is installed.
const PHP_DATA = join(OUT, "packages/php/data")
for (const f of ["allergens.json", "declarations.json", "codes.json", "icons.json"]) {
  writeFileSync(ensureDir(join(PHP_DATA, f)), readFileSync(join(DATA, f), "utf8"), "utf8")
}
for (const l of LOCALES) {
  writeFileSync(
    ensureDir(join(PHP_DATA, "bundles", `${l}.json`)),
    readFileSync(join(OUT, `data/bundles/${l}.json`), "utf8"),
    "utf8",
  )
}

// ------------------------------- packages/java/**/kotlin/**/Generated*.kt --
// Kotlin gets GENERATED SOURCE, for the same reason Dart does and a different
// one besides. The JVM has no JSON parser in its standard library, so reading
// the JSON at runtime would mean adding a dependency — and "no dependencies"
// is a property of this dataset worth keeping on every registry it reaches.
//
// One file PER LOCALE, not one big file. A JVM method body is capped at 64 KB
// of bytecode, and six locales of ~300 string constants in a single static
// initializer would sail past it — as a compile error that reads like a
// compiler bug rather than a size problem.
const kq = (v) => JSON.stringify(String(v))
const JAVA_SRC = join(OUT, "packages/java/src/main/kotlin/com/menuella/foodsafety")

for (const locale of LOCALES) {
  const b = JSON.parse(readFileSync(join(OUT, `data/bundles/${locale}.json`), "utf8"))
  writeFileSync(
    ensureDir(join(JAVA_SRC, `Bundle${locale.toUpperCase()}.kt`)),
    `// GENERATED by scripts/generate.mjs — do not edit by hand.
package com.menuella.foodsafety

internal fun bundle${locale.toUpperCase()}(): Disclosures = Disclosures(
  locale = ${kq(b.locale)},
  fallbackLocale = ${kq(b.fallbackLocale)},
  allergens = listOf(
${b.allergens.map((a) => `    Allergen(${kq(a.key)}, ${kq(a.group)}, ${a.isMember}, ${kq(a.icon)}, ${kq(a.name)}, ${kq(a.declaration)}, ${kq(a.description)}),`).join("\n")}
  ),
  declarations = listOf(
${b.declarations.map((d) => `    Declaration(${kq(d.key)}, ${kq(d.category)}, ${kq(d.icon)}, ${kq(d.name)}, ${kq(d.description)}),`).join("\n")}
  ),
)
`,
    "utf8",
  )
}

writeFileSync(
  ensureDir(join(JAVA_SRC, "GeneratedData.kt")),
  `// GENERATED by scripts/generate.mjs — do not edit by hand.
package com.menuella.foodsafety

internal val GENERATED_LOCALES: List<String> = listOf(${LOCALES.map(kq).join(", ")})
internal const val GENERATED_FALLBACK_LOCALE: String = ${kq(FALLBACK)}
internal const val GENERATED_CODE_SCHEME: String = ${kq(codes.scheme)}
internal val GENERATED_ALLERGEN_KEYS: List<String> = listOf(${A_KEYS.map(kq).join(", ")})
internal val GENERATED_DECLARATION_KEYS: List<String> = listOf(${D_KEYS.map(kq).join(", ")})

internal fun bundleFor(locale: String): Disclosures? = when (locale) {
${LOCALES.map((l) => `  ${kq(l)} -> bundle${l.toUpperCase()}()`).join("\n")}
  else -> null
}
`,
  "utf8",
)

writeFileSync(
  ensureDir(join(JAVA_SRC, "GeneratedIcons.kt")),
  `// GENERATED by scripts/generate.mjs from icons/*.svg — do not edit by hand.
package com.menuella.foodsafety

// Attribute names are already in SVG spelling here (fill-rule, not fillRule):
// there is no JSX on the JVM, so the React spelling would be wrong for every
// consumer of this binding.
internal fun generatedIcons(): Map<String, Icon> = mapOf(
${Object.entries(iconData).map(([name, icon]) => `  ${kq(name)} to Icon(
    viewBox = ${kq(icon.viewBox)},
    nodes = listOf(
${icon.nodes.map(([tag, attrs]) => {
  const pairs = Object.entries(attrs)
    .map(([k, v]) => `${kq(k === "fillRule" ? "fill-rule" : k === "clipRule" ? "clip-rule" : k)} to ${kq(v)}`)
    .join(", ")
  return `      IconNode(${kq(tag)}, linkedMapOf(${pairs})),`
}).join("\n")}
    ),
  ),`).join("\n")}
)
`,
  "utf8",
)

for (const f of ["CHANGELOG.md", "LICENSE"]) {
  writeFileSync(ensureDir(join(OUT, "packages/java", f)), readFileSync(join(ROOT, f), "utf8"), "utf8")
}


console.log(
  `generated  ${LOCALES.length} bundles (${LOCALES.join(", ")})  ·  index.js + index.d.ts` +
    `  ·  data/icons.json  ·  dart  ·  python` +
    `  ·  ${A_KEYS.length} allergens, ${D_KEYS.length} declarations, ${iconNames.length} icons`,
)
